/* automatically generated by rust-bindgen 0.72.1 */

pub const _STDINT_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC2Y: u32 = 0;
pub const __GLIBC_USE_ISOC23: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __TIMESIZE: u32 = 64;
pub const __USE_TIME_BITS64: u32 = 1;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const __GLIBC_USE_C23_STRTOL: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 42;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const _BITS_TYPES_H: u32 = 1;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __STATFS_MATCHES_STATFS64: u32 = 1;
pub const __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const _BITS_WCHAR_H: u32 = 1;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const _BITS_STDINT_LEAST_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i64 = -9223372036854775808;
pub const INT_FAST32_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u64 = 9223372036854775807;
pub const INT_FAST32_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: i32 = -1;
pub const UINT_FAST32_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const VAPOURSYNTH_API_MAJOR: u32 = 4;
pub const VAPOURSYNTH_API_MINOR: u32 = 0;
pub const VS_AUDIO_FRAME_SAMPLES: u32 = 3072;
pub const VSSCRIPT_API_MAJOR: u32 = 4;
pub const VSSCRIPT_API_MINOR: u32 = 1;
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __intmax_t = ::std::os::raw::c_long;
pub type __uintmax_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __fsid_t"][::std::mem::size_of::<__fsid_t>() - 8usize];
    ["Alignment of __fsid_t"][::std::mem::align_of::<__fsid_t>() - 4usize];
    ["Offset of field: __fsid_t::__val"][::std::mem::offset_of!(__fsid_t, __val) - 0usize];
};
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __suseconds64_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_long;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type __sig_atomic_t = ::std::os::raw::c_int;
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub type wchar_t = ::std::os::raw::c_int;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of max_align_t"][::std::mem::size_of::<max_align_t>() - 32usize];
    ["Alignment of max_align_t"][::std::mem::align_of::<max_align_t>() - 16usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce1"]
        [::std::mem::offset_of!(max_align_t, __clang_max_align_nonce1) - 0usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce2"]
        [::std::mem::offset_of!(max_align_t, __clang_max_align_nonce2) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VSFrame {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VSNode {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VSCore {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VSPlugin {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VSPluginFunction {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VSFunction {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VSMap {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VSLogHandle {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VSFrameContext {
    _unused: [u8; 0],
}
pub const VSColorFamily_cfUndefined: VSColorFamily = 0;
pub const VSColorFamily_cfGray: VSColorFamily = 1;
pub const VSColorFamily_cfRGB: VSColorFamily = 2;
pub const VSColorFamily_cfYUV: VSColorFamily = 3;
pub type VSColorFamily = ::std::os::raw::c_uint;
pub const VSSampleType_stInteger: VSSampleType = 0;
pub const VSSampleType_stFloat: VSSampleType = 1;
pub type VSSampleType = ::std::os::raw::c_uint;
pub const VSPresetVideoFormat_pfNone: VSPresetVideoFormat = 0;
pub const VSPresetVideoFormat_pfGray8: VSPresetVideoFormat = 268959744;
pub const VSPresetVideoFormat_pfGray9: VSPresetVideoFormat = 269025280;
pub const VSPresetVideoFormat_pfGray10: VSPresetVideoFormat = 269090816;
pub const VSPresetVideoFormat_pfGray12: VSPresetVideoFormat = 269221888;
pub const VSPresetVideoFormat_pfGray14: VSPresetVideoFormat = 269352960;
pub const VSPresetVideoFormat_pfGray16: VSPresetVideoFormat = 269484032;
pub const VSPresetVideoFormat_pfGray32: VSPresetVideoFormat = 270532608;
pub const VSPresetVideoFormat_pfGrayH: VSPresetVideoFormat = 286261248;
pub const VSPresetVideoFormat_pfGrayS: VSPresetVideoFormat = 287309824;
pub const VSPresetVideoFormat_pfYUV410P8: VSPresetVideoFormat = 805831170;
pub const VSPresetVideoFormat_pfYUV411P8: VSPresetVideoFormat = 805831168;
pub const VSPresetVideoFormat_pfYUV440P8: VSPresetVideoFormat = 805830657;
pub const VSPresetVideoFormat_pfYUV420P8: VSPresetVideoFormat = 805830913;
pub const VSPresetVideoFormat_pfYUV422P8: VSPresetVideoFormat = 805830912;
pub const VSPresetVideoFormat_pfYUV444P8: VSPresetVideoFormat = 805830656;
pub const VSPresetVideoFormat_pfYUV420P9: VSPresetVideoFormat = 805896449;
pub const VSPresetVideoFormat_pfYUV422P9: VSPresetVideoFormat = 805896448;
pub const VSPresetVideoFormat_pfYUV444P9: VSPresetVideoFormat = 805896192;
pub const VSPresetVideoFormat_pfYUV420P10: VSPresetVideoFormat = 805961985;
pub const VSPresetVideoFormat_pfYUV422P10: VSPresetVideoFormat = 805961984;
pub const VSPresetVideoFormat_pfYUV444P10: VSPresetVideoFormat = 805961728;
pub const VSPresetVideoFormat_pfYUV420P12: VSPresetVideoFormat = 806093057;
pub const VSPresetVideoFormat_pfYUV422P12: VSPresetVideoFormat = 806093056;
pub const VSPresetVideoFormat_pfYUV444P12: VSPresetVideoFormat = 806092800;
pub const VSPresetVideoFormat_pfYUV420P14: VSPresetVideoFormat = 806224129;
pub const VSPresetVideoFormat_pfYUV422P14: VSPresetVideoFormat = 806224128;
pub const VSPresetVideoFormat_pfYUV444P14: VSPresetVideoFormat = 806223872;
pub const VSPresetVideoFormat_pfYUV420P16: VSPresetVideoFormat = 806355201;
pub const VSPresetVideoFormat_pfYUV422P16: VSPresetVideoFormat = 806355200;
pub const VSPresetVideoFormat_pfYUV444P16: VSPresetVideoFormat = 806354944;
pub const VSPresetVideoFormat_pfYUV420PH: VSPresetVideoFormat = 823132417;
pub const VSPresetVideoFormat_pfYUV420PS: VSPresetVideoFormat = 824180993;
pub const VSPresetVideoFormat_pfYUV422PH: VSPresetVideoFormat = 823132416;
pub const VSPresetVideoFormat_pfYUV422PS: VSPresetVideoFormat = 824180992;
pub const VSPresetVideoFormat_pfYUV444PH: VSPresetVideoFormat = 823132160;
pub const VSPresetVideoFormat_pfYUV444PS: VSPresetVideoFormat = 824180736;
pub const VSPresetVideoFormat_pfRGB24: VSPresetVideoFormat = 537395200;
pub const VSPresetVideoFormat_pfRGB27: VSPresetVideoFormat = 537460736;
pub const VSPresetVideoFormat_pfRGB30: VSPresetVideoFormat = 537526272;
pub const VSPresetVideoFormat_pfRGB36: VSPresetVideoFormat = 537657344;
pub const VSPresetVideoFormat_pfRGB42: VSPresetVideoFormat = 537788416;
pub const VSPresetVideoFormat_pfRGB48: VSPresetVideoFormat = 537919488;
pub const VSPresetVideoFormat_pfRGBH: VSPresetVideoFormat = 554696704;
pub const VSPresetVideoFormat_pfRGBS: VSPresetVideoFormat = 555745280;
pub type VSPresetVideoFormat = ::std::os::raw::c_uint;
pub const VSFilterMode_fmParallel: VSFilterMode = 0;
pub const VSFilterMode_fmParallelRequests: VSFilterMode = 1;
pub const VSFilterMode_fmUnordered: VSFilterMode = 2;
pub const VSFilterMode_fmFrameState: VSFilterMode = 3;
pub type VSFilterMode = ::std::os::raw::c_uint;
pub const VSMediaType_mtVideo: VSMediaType = 1;
pub const VSMediaType_mtAudio: VSMediaType = 2;
pub type VSMediaType = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VSVideoFormat {
    pub colorFamily: ::std::os::raw::c_int,
    pub sampleType: ::std::os::raw::c_int,
    pub bitsPerSample: ::std::os::raw::c_int,
    pub bytesPerSample: ::std::os::raw::c_int,
    pub subSamplingW: ::std::os::raw::c_int,
    pub subSamplingH: ::std::os::raw::c_int,
    pub numPlanes: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VSVideoFormat"][::std::mem::size_of::<VSVideoFormat>() - 28usize];
    ["Alignment of VSVideoFormat"][::std::mem::align_of::<VSVideoFormat>() - 4usize];
    ["Offset of field: VSVideoFormat::colorFamily"]
        [::std::mem::offset_of!(VSVideoFormat, colorFamily) - 0usize];
    ["Offset of field: VSVideoFormat::sampleType"]
        [::std::mem::offset_of!(VSVideoFormat, sampleType) - 4usize];
    ["Offset of field: VSVideoFormat::bitsPerSample"]
        [::std::mem::offset_of!(VSVideoFormat, bitsPerSample) - 8usize];
    ["Offset of field: VSVideoFormat::bytesPerSample"]
        [::std::mem::offset_of!(VSVideoFormat, bytesPerSample) - 12usize];
    ["Offset of field: VSVideoFormat::subSamplingW"]
        [::std::mem::offset_of!(VSVideoFormat, subSamplingW) - 16usize];
    ["Offset of field: VSVideoFormat::subSamplingH"]
        [::std::mem::offset_of!(VSVideoFormat, subSamplingH) - 20usize];
    ["Offset of field: VSVideoFormat::numPlanes"]
        [::std::mem::offset_of!(VSVideoFormat, numPlanes) - 24usize];
};
pub const VSAudioChannels_acFrontLeft: VSAudioChannels = 0;
pub const VSAudioChannels_acFrontRight: VSAudioChannels = 1;
pub const VSAudioChannels_acFrontCenter: VSAudioChannels = 2;
pub const VSAudioChannels_acLowFrequency: VSAudioChannels = 3;
pub const VSAudioChannels_acBackLeft: VSAudioChannels = 4;
pub const VSAudioChannels_acBackRight: VSAudioChannels = 5;
pub const VSAudioChannels_acFrontLeftOFCenter: VSAudioChannels = 6;
pub const VSAudioChannels_acFrontRightOFCenter: VSAudioChannels = 7;
pub const VSAudioChannels_acBackCenter: VSAudioChannels = 8;
pub const VSAudioChannels_acSideLeft: VSAudioChannels = 9;
pub const VSAudioChannels_acSideRight: VSAudioChannels = 10;
pub const VSAudioChannels_acTopCenter: VSAudioChannels = 11;
pub const VSAudioChannels_acTopFrontLeft: VSAudioChannels = 12;
pub const VSAudioChannels_acTopFrontCenter: VSAudioChannels = 13;
pub const VSAudioChannels_acTopFrontRight: VSAudioChannels = 14;
pub const VSAudioChannels_acTopBackLeft: VSAudioChannels = 15;
pub const VSAudioChannels_acTopBackCenter: VSAudioChannels = 16;
pub const VSAudioChannels_acTopBackRight: VSAudioChannels = 17;
pub const VSAudioChannels_acStereoLeft: VSAudioChannels = 29;
pub const VSAudioChannels_acStereoRight: VSAudioChannels = 30;
pub const VSAudioChannels_acWideLeft: VSAudioChannels = 31;
pub const VSAudioChannels_acWideRight: VSAudioChannels = 32;
pub const VSAudioChannels_acSurroundDirectLeft: VSAudioChannels = 33;
pub const VSAudioChannels_acSurroundDirectRight: VSAudioChannels = 34;
pub const VSAudioChannels_acLowFrequency2: VSAudioChannels = 35;
pub type VSAudioChannels = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VSAudioFormat {
    pub sampleType: ::std::os::raw::c_int,
    pub bitsPerSample: ::std::os::raw::c_int,
    pub bytesPerSample: ::std::os::raw::c_int,
    pub numChannels: ::std::os::raw::c_int,
    pub channelLayout: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VSAudioFormat"][::std::mem::size_of::<VSAudioFormat>() - 24usize];
    ["Alignment of VSAudioFormat"][::std::mem::align_of::<VSAudioFormat>() - 8usize];
    ["Offset of field: VSAudioFormat::sampleType"]
        [::std::mem::offset_of!(VSAudioFormat, sampleType) - 0usize];
    ["Offset of field: VSAudioFormat::bitsPerSample"]
        [::std::mem::offset_of!(VSAudioFormat, bitsPerSample) - 4usize];
    ["Offset of field: VSAudioFormat::bytesPerSample"]
        [::std::mem::offset_of!(VSAudioFormat, bytesPerSample) - 8usize];
    ["Offset of field: VSAudioFormat::numChannels"]
        [::std::mem::offset_of!(VSAudioFormat, numChannels) - 12usize];
    ["Offset of field: VSAudioFormat::channelLayout"]
        [::std::mem::offset_of!(VSAudioFormat, channelLayout) - 16usize];
};
pub const VSPropertyType_ptUnset: VSPropertyType = 0;
pub const VSPropertyType_ptInt: VSPropertyType = 1;
pub const VSPropertyType_ptFloat: VSPropertyType = 2;
pub const VSPropertyType_ptData: VSPropertyType = 3;
pub const VSPropertyType_ptFunction: VSPropertyType = 4;
pub const VSPropertyType_ptVideoNode: VSPropertyType = 5;
pub const VSPropertyType_ptAudioNode: VSPropertyType = 6;
pub const VSPropertyType_ptVideoFrame: VSPropertyType = 7;
pub const VSPropertyType_ptAudioFrame: VSPropertyType = 8;
pub type VSPropertyType = ::std::os::raw::c_uint;
pub const VSMapPropertyError_peSuccess: VSMapPropertyError = 0;
pub const VSMapPropertyError_peUnset: VSMapPropertyError = 1;
pub const VSMapPropertyError_peType: VSMapPropertyError = 2;
pub const VSMapPropertyError_peIndex: VSMapPropertyError = 4;
pub const VSMapPropertyError_peError: VSMapPropertyError = 3;
pub type VSMapPropertyError = ::std::os::raw::c_uint;
pub const VSMapAppendMode_maReplace: VSMapAppendMode = 0;
pub const VSMapAppendMode_maAppend: VSMapAppendMode = 1;
pub type VSMapAppendMode = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VSCoreInfo {
    pub versionString: *const ::std::os::raw::c_char,
    pub core: ::std::os::raw::c_int,
    pub api: ::std::os::raw::c_int,
    pub numThreads: ::std::os::raw::c_int,
    pub maxFramebufferSize: i64,
    pub usedFramebufferSize: i64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VSCoreInfo"][::std::mem::size_of::<VSCoreInfo>() - 40usize];
    ["Alignment of VSCoreInfo"][::std::mem::align_of::<VSCoreInfo>() - 8usize];
    ["Offset of field: VSCoreInfo::versionString"]
        [::std::mem::offset_of!(VSCoreInfo, versionString) - 0usize];
    ["Offset of field: VSCoreInfo::core"][::std::mem::offset_of!(VSCoreInfo, core) - 8usize];
    ["Offset of field: VSCoreInfo::api"][::std::mem::offset_of!(VSCoreInfo, api) - 12usize];
    ["Offset of field: VSCoreInfo::numThreads"]
        [::std::mem::offset_of!(VSCoreInfo, numThreads) - 16usize];
    ["Offset of field: VSCoreInfo::maxFramebufferSize"]
        [::std::mem::offset_of!(VSCoreInfo, maxFramebufferSize) - 24usize];
    ["Offset of field: VSCoreInfo::usedFramebufferSize"]
        [::std::mem::offset_of!(VSCoreInfo, usedFramebufferSize) - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VSVideoInfo {
    pub format: VSVideoFormat,
    pub fpsNum: i64,
    pub fpsDen: i64,
    pub width: ::std::os::raw::c_int,
    pub height: ::std::os::raw::c_int,
    pub numFrames: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VSVideoInfo"][::std::mem::size_of::<VSVideoInfo>() - 64usize];
    ["Alignment of VSVideoInfo"][::std::mem::align_of::<VSVideoInfo>() - 8usize];
    ["Offset of field: VSVideoInfo::format"][::std::mem::offset_of!(VSVideoInfo, format) - 0usize];
    ["Offset of field: VSVideoInfo::fpsNum"][::std::mem::offset_of!(VSVideoInfo, fpsNum) - 32usize];
    ["Offset of field: VSVideoInfo::fpsDen"][::std::mem::offset_of!(VSVideoInfo, fpsDen) - 40usize];
    ["Offset of field: VSVideoInfo::width"][::std::mem::offset_of!(VSVideoInfo, width) - 48usize];
    ["Offset of field: VSVideoInfo::height"][::std::mem::offset_of!(VSVideoInfo, height) - 52usize];
    ["Offset of field: VSVideoInfo::numFrames"]
        [::std::mem::offset_of!(VSVideoInfo, numFrames) - 56usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VSAudioInfo {
    pub format: VSAudioFormat,
    pub sampleRate: ::std::os::raw::c_int,
    pub numSamples: i64,
    pub numFrames: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VSAudioInfo"][::std::mem::size_of::<VSAudioInfo>() - 48usize];
    ["Alignment of VSAudioInfo"][::std::mem::align_of::<VSAudioInfo>() - 8usize];
    ["Offset of field: VSAudioInfo::format"][::std::mem::offset_of!(VSAudioInfo, format) - 0usize];
    ["Offset of field: VSAudioInfo::sampleRate"]
        [::std::mem::offset_of!(VSAudioInfo, sampleRate) - 24usize];
    ["Offset of field: VSAudioInfo::numSamples"]
        [::std::mem::offset_of!(VSAudioInfo, numSamples) - 32usize];
    ["Offset of field: VSAudioInfo::numFrames"]
        [::std::mem::offset_of!(VSAudioInfo, numFrames) - 40usize];
};
pub const VSActivationReason_arInitial: VSActivationReason = 0;
pub const VSActivationReason_arAllFramesReady: VSActivationReason = 1;
pub const VSActivationReason_arError: VSActivationReason = -1;
pub type VSActivationReason = ::std::os::raw::c_int;
pub const VSMessageType_mtDebug: VSMessageType = 0;
pub const VSMessageType_mtInformation: VSMessageType = 1;
pub const VSMessageType_mtWarning: VSMessageType = 2;
pub const VSMessageType_mtCritical: VSMessageType = 3;
pub const VSMessageType_mtFatal: VSMessageType = 4;
pub type VSMessageType = ::std::os::raw::c_uint;
pub const VSCoreCreationFlags_ccfEnableGraphInspection: VSCoreCreationFlags = 1;
pub const VSCoreCreationFlags_ccfDisableAutoLoading: VSCoreCreationFlags = 2;
pub const VSCoreCreationFlags_ccfDisableLibraryUnloading: VSCoreCreationFlags = 4;
pub type VSCoreCreationFlags = ::std::os::raw::c_uint;
pub const VSPluginConfigFlags_pcModifiable: VSPluginConfigFlags = 1;
pub type VSPluginConfigFlags = ::std::os::raw::c_uint;
pub const VSDataTypeHint_dtUnknown: VSDataTypeHint = -1;
pub const VSDataTypeHint_dtBinary: VSDataTypeHint = 0;
pub const VSDataTypeHint_dtUtf8: VSDataTypeHint = 1;
pub type VSDataTypeHint = ::std::os::raw::c_int;
pub const VSRequestPattern_rpGeneral: VSRequestPattern = 0;
pub const VSRequestPattern_rpNoFrameReuse: VSRequestPattern = 1;
pub const VSRequestPattern_rpStrictSpatial: VSRequestPattern = 2;
pub type VSRequestPattern = ::std::os::raw::c_uint;
pub const VSCacheMode_cmAuto: VSCacheMode = -1;
pub const VSCacheMode_cmForceDisable: VSCacheMode = 0;
pub const VSCacheMode_cmForceEnable: VSCacheMode = 1;
pub type VSCacheMode = ::std::os::raw::c_int;
pub type VSGetVapourSynthAPI =
    ::std::option::Option<unsafe extern "C" fn(version: ::std::os::raw::c_int) -> *const VSAPI>;
pub type VSPublicFunction = ::std::option::Option<
    unsafe extern "C" fn(
        in_: *const VSMap,
        out: *mut VSMap,
        userData: *mut ::std::os::raw::c_void,
        core: *mut VSCore,
        vsapi: *const VSAPI,
    ),
>;
pub type VSInitPlugin =
    ::std::option::Option<unsafe extern "C" fn(plugin: *mut VSPlugin, vspapi: *const VSPLUGINAPI)>;
pub type VSFreeFunctionData =
    ::std::option::Option<unsafe extern "C" fn(userData: *mut ::std::os::raw::c_void)>;
pub type VSFilterGetFrame = ::std::option::Option<
    unsafe extern "C" fn(
        n: ::std::os::raw::c_int,
        activationReason: ::std::os::raw::c_int,
        instanceData: *mut ::std::os::raw::c_void,
        frameData: *mut *mut ::std::os::raw::c_void,
        frameCtx: *mut VSFrameContext,
        core: *mut VSCore,
        vsapi: *const VSAPI,
    ) -> *const VSFrame,
>;
pub type VSFilterFree = ::std::option::Option<
    unsafe extern "C" fn(
        instanceData: *mut ::std::os::raw::c_void,
        core: *mut VSCore,
        vsapi: *const VSAPI,
    ),
>;
pub type VSFrameDoneCallback = ::std::option::Option<
    unsafe extern "C" fn(
        userData: *mut ::std::os::raw::c_void,
        f: *const VSFrame,
        n: ::std::os::raw::c_int,
        node: *mut VSNode,
        errorMsg: *const ::std::os::raw::c_char,
    ),
>;
pub type VSLogHandler = ::std::option::Option<
    unsafe extern "C" fn(
        msgType: ::std::os::raw::c_int,
        msg: *const ::std::os::raw::c_char,
        userData: *mut ::std::os::raw::c_void,
    ),
>;
pub type VSLogHandlerFree =
    ::std::option::Option<unsafe extern "C" fn(userData: *mut ::std::os::raw::c_void)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VSPLUGINAPI {
    pub getAPIVersion: ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>,
    pub configPlugin: ::std::option::Option<
        unsafe extern "C" fn(
            identifier: *const ::std::os::raw::c_char,
            pluginNamespace: *const ::std::os::raw::c_char,
            name: *const ::std::os::raw::c_char,
            pluginVersion: ::std::os::raw::c_int,
            apiVersion: ::std::os::raw::c_int,
            flags: ::std::os::raw::c_int,
            plugin: *mut VSPlugin,
        ) -> ::std::os::raw::c_int,
    >,
    pub registerFunction: ::std::option::Option<
        unsafe extern "C" fn(
            name: *const ::std::os::raw::c_char,
            args: *const ::std::os::raw::c_char,
            returnType: *const ::std::os::raw::c_char,
            argsFunc: VSPublicFunction,
            functionData: *mut ::std::os::raw::c_void,
            plugin: *mut VSPlugin,
        ) -> ::std::os::raw::c_int,
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VSPLUGINAPI"][::std::mem::size_of::<VSPLUGINAPI>() - 24usize];
    ["Alignment of VSPLUGINAPI"][::std::mem::align_of::<VSPLUGINAPI>() - 8usize];
    ["Offset of field: VSPLUGINAPI::getAPIVersion"]
        [::std::mem::offset_of!(VSPLUGINAPI, getAPIVersion) - 0usize];
    ["Offset of field: VSPLUGINAPI::configPlugin"]
        [::std::mem::offset_of!(VSPLUGINAPI, configPlugin) - 8usize];
    ["Offset of field: VSPLUGINAPI::registerFunction"]
        [::std::mem::offset_of!(VSPLUGINAPI, registerFunction) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VSFilterDependency {
    pub source: *mut VSNode,
    pub requestPattern: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VSFilterDependency"][::std::mem::size_of::<VSFilterDependency>() - 16usize];
    ["Alignment of VSFilterDependency"][::std::mem::align_of::<VSFilterDependency>() - 8usize];
    ["Offset of field: VSFilterDependency::source"]
        [::std::mem::offset_of!(VSFilterDependency, source) - 0usize];
    ["Offset of field: VSFilterDependency::requestPattern"]
        [::std::mem::offset_of!(VSFilterDependency, requestPattern) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VSAPI {
    pub createVideoFilter: ::std::option::Option<
        unsafe extern "C" fn(
            out: *mut VSMap,
            name: *const ::std::os::raw::c_char,
            vi: *const VSVideoInfo,
            getFrame: VSFilterGetFrame,
            free: VSFilterFree,
            filterMode: ::std::os::raw::c_int,
            dependencies: *const VSFilterDependency,
            numDeps: ::std::os::raw::c_int,
            instanceData: *mut ::std::os::raw::c_void,
            core: *mut VSCore,
        ),
    >,
    pub createVideoFilter2: ::std::option::Option<
        unsafe extern "C" fn(
            name: *const ::std::os::raw::c_char,
            vi: *const VSVideoInfo,
            getFrame: VSFilterGetFrame,
            free: VSFilterFree,
            filterMode: ::std::os::raw::c_int,
            dependencies: *const VSFilterDependency,
            numDeps: ::std::os::raw::c_int,
            instanceData: *mut ::std::os::raw::c_void,
            core: *mut VSCore,
        ) -> *mut VSNode,
    >,
    pub createAudioFilter: ::std::option::Option<
        unsafe extern "C" fn(
            out: *mut VSMap,
            name: *const ::std::os::raw::c_char,
            ai: *const VSAudioInfo,
            getFrame: VSFilterGetFrame,
            free: VSFilterFree,
            filterMode: ::std::os::raw::c_int,
            dependencies: *const VSFilterDependency,
            numDeps: ::std::os::raw::c_int,
            instanceData: *mut ::std::os::raw::c_void,
            core: *mut VSCore,
        ),
    >,
    pub createAudioFilter2: ::std::option::Option<
        unsafe extern "C" fn(
            name: *const ::std::os::raw::c_char,
            ai: *const VSAudioInfo,
            getFrame: VSFilterGetFrame,
            free: VSFilterFree,
            filterMode: ::std::os::raw::c_int,
            dependencies: *const VSFilterDependency,
            numDeps: ::std::os::raw::c_int,
            instanceData: *mut ::std::os::raw::c_void,
            core: *mut VSCore,
        ) -> *mut VSNode,
    >,
    pub setLinearFilter:
        ::std::option::Option<unsafe extern "C" fn(node: *mut VSNode) -> ::std::os::raw::c_int>,
    pub setCacheMode:
        ::std::option::Option<unsafe extern "C" fn(node: *mut VSNode, mode: ::std::os::raw::c_int)>,
    pub setCacheOptions: ::std::option::Option<
        unsafe extern "C" fn(
            node: *mut VSNode,
            fixedSize: ::std::os::raw::c_int,
            maxSize: ::std::os::raw::c_int,
            maxHistorySize: ::std::os::raw::c_int,
        ),
    >,
    pub freeNode: ::std::option::Option<unsafe extern "C" fn(node: *mut VSNode)>,
    pub addNodeRef: ::std::option::Option<unsafe extern "C" fn(node: *mut VSNode) -> *mut VSNode>,
    pub getNodeType:
        ::std::option::Option<unsafe extern "C" fn(node: *mut VSNode) -> ::std::os::raw::c_int>,
    pub getVideoInfo:
        ::std::option::Option<unsafe extern "C" fn(node: *mut VSNode) -> *const VSVideoInfo>,
    pub getAudioInfo:
        ::std::option::Option<unsafe extern "C" fn(node: *mut VSNode) -> *const VSAudioInfo>,
    pub newVideoFrame: ::std::option::Option<
        unsafe extern "C" fn(
            format: *const VSVideoFormat,
            width: ::std::os::raw::c_int,
            height: ::std::os::raw::c_int,
            propSrc: *const VSFrame,
            core: *mut VSCore,
        ) -> *mut VSFrame,
    >,
    pub newVideoFrame2: ::std::option::Option<
        unsafe extern "C" fn(
            format: *const VSVideoFormat,
            width: ::std::os::raw::c_int,
            height: ::std::os::raw::c_int,
            planeSrc: *mut *const VSFrame,
            planes: *const ::std::os::raw::c_int,
            propSrc: *const VSFrame,
            core: *mut VSCore,
        ) -> *mut VSFrame,
    >,
    pub newAudioFrame: ::std::option::Option<
        unsafe extern "C" fn(
            format: *const VSAudioFormat,
            numSamples: ::std::os::raw::c_int,
            propSrc: *const VSFrame,
            core: *mut VSCore,
        ) -> *mut VSFrame,
    >,
    pub newAudioFrame2: ::std::option::Option<
        unsafe extern "C" fn(
            format: *const VSAudioFormat,
            numSamples: ::std::os::raw::c_int,
            channelSrc: *mut *const VSFrame,
            channels: *const ::std::os::raw::c_int,
            propSrc: *const VSFrame,
            core: *mut VSCore,
        ) -> *mut VSFrame,
    >,
    pub freeFrame: ::std::option::Option<unsafe extern "C" fn(f: *const VSFrame)>,
    pub addFrameRef:
        ::std::option::Option<unsafe extern "C" fn(f: *const VSFrame) -> *const VSFrame>,
    pub copyFrame: ::std::option::Option<
        unsafe extern "C" fn(f: *const VSFrame, core: *mut VSCore) -> *mut VSFrame,
    >,
    pub getFramePropertiesRO:
        ::std::option::Option<unsafe extern "C" fn(f: *const VSFrame) -> *const VSMap>,
    pub getFramePropertiesRW:
        ::std::option::Option<unsafe extern "C" fn(f: *mut VSFrame) -> *mut VSMap>,
    pub getStride: ::std::option::Option<
        unsafe extern "C" fn(f: *const VSFrame, plane: ::std::os::raw::c_int) -> isize,
    >,
    pub getReadPtr: ::std::option::Option<
        unsafe extern "C" fn(f: *const VSFrame, plane: ::std::os::raw::c_int) -> *const u8,
    >,
    pub getWritePtr: ::std::option::Option<
        unsafe extern "C" fn(f: *mut VSFrame, plane: ::std::os::raw::c_int) -> *mut u8,
    >,
    pub getVideoFrameFormat:
        ::std::option::Option<unsafe extern "C" fn(f: *const VSFrame) -> *const VSVideoFormat>,
    pub getAudioFrameFormat:
        ::std::option::Option<unsafe extern "C" fn(f: *const VSFrame) -> *const VSAudioFormat>,
    pub getFrameType:
        ::std::option::Option<unsafe extern "C" fn(f: *const VSFrame) -> ::std::os::raw::c_int>,
    pub getFrameWidth: ::std::option::Option<
        unsafe extern "C" fn(
            f: *const VSFrame,
            plane: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub getFrameHeight: ::std::option::Option<
        unsafe extern "C" fn(
            f: *const VSFrame,
            plane: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub getFrameLength:
        ::std::option::Option<unsafe extern "C" fn(f: *const VSFrame) -> ::std::os::raw::c_int>,
    pub getVideoFormatName: ::std::option::Option<
        unsafe extern "C" fn(
            format: *const VSVideoFormat,
            buffer: *mut ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub getAudioFormatName: ::std::option::Option<
        unsafe extern "C" fn(
            format: *const VSAudioFormat,
            buffer: *mut ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub queryVideoFormat: ::std::option::Option<
        unsafe extern "C" fn(
            format: *mut VSVideoFormat,
            colorFamily: ::std::os::raw::c_int,
            sampleType: ::std::os::raw::c_int,
            bitsPerSample: ::std::os::raw::c_int,
            subSamplingW: ::std::os::raw::c_int,
            subSamplingH: ::std::os::raw::c_int,
            core: *mut VSCore,
        ) -> ::std::os::raw::c_int,
    >,
    pub queryAudioFormat: ::std::option::Option<
        unsafe extern "C" fn(
            format: *mut VSAudioFormat,
            sampleType: ::std::os::raw::c_int,
            bitsPerSample: ::std::os::raw::c_int,
            channelLayout: u64,
            core: *mut VSCore,
        ) -> ::std::os::raw::c_int,
    >,
    pub queryVideoFormatID: ::std::option::Option<
        unsafe extern "C" fn(
            colorFamily: ::std::os::raw::c_int,
            sampleType: ::std::os::raw::c_int,
            bitsPerSample: ::std::os::raw::c_int,
            subSamplingW: ::std::os::raw::c_int,
            subSamplingH: ::std::os::raw::c_int,
            core: *mut VSCore,
        ) -> u32,
    >,
    pub getVideoFormatByID: ::std::option::Option<
        unsafe extern "C" fn(
            format: *mut VSVideoFormat,
            id: u32,
            core: *mut VSCore,
        ) -> ::std::os::raw::c_int,
    >,
    pub getFrame: ::std::option::Option<
        unsafe extern "C" fn(
            n: ::std::os::raw::c_int,
            node: *mut VSNode,
            errorMsg: *mut ::std::os::raw::c_char,
            bufSize: ::std::os::raw::c_int,
        ) -> *const VSFrame,
    >,
    pub getFrameAsync: ::std::option::Option<
        unsafe extern "C" fn(
            n: ::std::os::raw::c_int,
            node: *mut VSNode,
            callback: VSFrameDoneCallback,
            userData: *mut ::std::os::raw::c_void,
        ),
    >,
    pub getFrameFilter: ::std::option::Option<
        unsafe extern "C" fn(
            n: ::std::os::raw::c_int,
            node: *mut VSNode,
            frameCtx: *mut VSFrameContext,
        ) -> *const VSFrame,
    >,
    pub requestFrameFilter: ::std::option::Option<
        unsafe extern "C" fn(
            n: ::std::os::raw::c_int,
            node: *mut VSNode,
            frameCtx: *mut VSFrameContext,
        ),
    >,
    pub releaseFrameEarly: ::std::option::Option<
        unsafe extern "C" fn(
            node: *mut VSNode,
            n: ::std::os::raw::c_int,
            frameCtx: *mut VSFrameContext,
        ),
    >,
    pub cacheFrame: ::std::option::Option<
        unsafe extern "C" fn(
            frame: *const VSFrame,
            n: ::std::os::raw::c_int,
            frameCtx: *mut VSFrameContext,
        ),
    >,
    pub setFilterError: ::std::option::Option<
        unsafe extern "C" fn(
            errorMessage: *const ::std::os::raw::c_char,
            frameCtx: *mut VSFrameContext,
        ),
    >,
    pub createFunction: ::std::option::Option<
        unsafe extern "C" fn(
            func: VSPublicFunction,
            userData: *mut ::std::os::raw::c_void,
            free: VSFreeFunctionData,
            core: *mut VSCore,
        ) -> *mut VSFunction,
    >,
    pub freeFunction: ::std::option::Option<unsafe extern "C" fn(f: *mut VSFunction)>,
    pub addFunctionRef:
        ::std::option::Option<unsafe extern "C" fn(f: *mut VSFunction) -> *mut VSFunction>,
    pub callFunction: ::std::option::Option<
        unsafe extern "C" fn(func: *mut VSFunction, in_: *const VSMap, out: *mut VSMap),
    >,
    pub createMap: ::std::option::Option<unsafe extern "C" fn() -> *mut VSMap>,
    pub freeMap: ::std::option::Option<unsafe extern "C" fn(map: *mut VSMap)>,
    pub clearMap: ::std::option::Option<unsafe extern "C" fn(map: *mut VSMap)>,
    pub copyMap: ::std::option::Option<unsafe extern "C" fn(src: *const VSMap, dst: *mut VSMap)>,
    pub mapSetError: ::std::option::Option<
        unsafe extern "C" fn(map: *mut VSMap, errorMessage: *const ::std::os::raw::c_char),
    >,
    pub mapGetError: ::std::option::Option<
        unsafe extern "C" fn(map: *const VSMap) -> *const ::std::os::raw::c_char,
    >,
    pub mapNumKeys:
        ::std::option::Option<unsafe extern "C" fn(map: *const VSMap) -> ::std::os::raw::c_int>,
    pub mapGetKey: ::std::option::Option<
        unsafe extern "C" fn(
            map: *const VSMap,
            index: ::std::os::raw::c_int,
        ) -> *const ::std::os::raw::c_char,
    >,
    pub mapDeleteKey: ::std::option::Option<
        unsafe extern "C" fn(
            map: *mut VSMap,
            key: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub mapNumElements: ::std::option::Option<
        unsafe extern "C" fn(
            map: *const VSMap,
            key: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub mapGetType: ::std::option::Option<
        unsafe extern "C" fn(
            map: *const VSMap,
            key: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub mapSetEmpty: ::std::option::Option<
        unsafe extern "C" fn(
            map: *mut VSMap,
            key: *const ::std::os::raw::c_char,
            type_: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub mapGetInt: ::std::option::Option<
        unsafe extern "C" fn(
            map: *const VSMap,
            key: *const ::std::os::raw::c_char,
            index: ::std::os::raw::c_int,
            error: *mut ::std::os::raw::c_int,
        ) -> i64,
    >,
    pub mapGetIntSaturated: ::std::option::Option<
        unsafe extern "C" fn(
            map: *const VSMap,
            key: *const ::std::os::raw::c_char,
            index: ::std::os::raw::c_int,
            error: *mut ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub mapGetIntArray: ::std::option::Option<
        unsafe extern "C" fn(
            map: *const VSMap,
            key: *const ::std::os::raw::c_char,
            error: *mut ::std::os::raw::c_int,
        ) -> *const i64,
    >,
    pub mapSetInt: ::std::option::Option<
        unsafe extern "C" fn(
            map: *mut VSMap,
            key: *const ::std::os::raw::c_char,
            i: i64,
            append: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub mapSetIntArray: ::std::option::Option<
        unsafe extern "C" fn(
            map: *mut VSMap,
            key: *const ::std::os::raw::c_char,
            i: *const i64,
            size: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub mapGetFloat: ::std::option::Option<
        unsafe extern "C" fn(
            map: *const VSMap,
            key: *const ::std::os::raw::c_char,
            index: ::std::os::raw::c_int,
            error: *mut ::std::os::raw::c_int,
        ) -> f64,
    >,
    pub mapGetFloatSaturated: ::std::option::Option<
        unsafe extern "C" fn(
            map: *const VSMap,
            key: *const ::std::os::raw::c_char,
            index: ::std::os::raw::c_int,
            error: *mut ::std::os::raw::c_int,
        ) -> f32,
    >,
    pub mapGetFloatArray: ::std::option::Option<
        unsafe extern "C" fn(
            map: *const VSMap,
            key: *const ::std::os::raw::c_char,
            error: *mut ::std::os::raw::c_int,
        ) -> *const f64,
    >,
    pub mapSetFloat: ::std::option::Option<
        unsafe extern "C" fn(
            map: *mut VSMap,
            key: *const ::std::os::raw::c_char,
            d: f64,
            append: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub mapSetFloatArray: ::std::option::Option<
        unsafe extern "C" fn(
            map: *mut VSMap,
            key: *const ::std::os::raw::c_char,
            d: *const f64,
            size: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub mapGetData: ::std::option::Option<
        unsafe extern "C" fn(
            map: *const VSMap,
            key: *const ::std::os::raw::c_char,
            index: ::std::os::raw::c_int,
            error: *mut ::std::os::raw::c_int,
        ) -> *const ::std::os::raw::c_char,
    >,
    pub mapGetDataSize: ::std::option::Option<
        unsafe extern "C" fn(
            map: *const VSMap,
            key: *const ::std::os::raw::c_char,
            index: ::std::os::raw::c_int,
            error: *mut ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub mapGetDataTypeHint: ::std::option::Option<
        unsafe extern "C" fn(
            map: *const VSMap,
            key: *const ::std::os::raw::c_char,
            index: ::std::os::raw::c_int,
            error: *mut ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub mapSetData: ::std::option::Option<
        unsafe extern "C" fn(
            map: *mut VSMap,
            key: *const ::std::os::raw::c_char,
            data: *const ::std::os::raw::c_char,
            size: ::std::os::raw::c_int,
            type_: ::std::os::raw::c_int,
            append: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub mapGetNode: ::std::option::Option<
        unsafe extern "C" fn(
            map: *const VSMap,
            key: *const ::std::os::raw::c_char,
            index: ::std::os::raw::c_int,
            error: *mut ::std::os::raw::c_int,
        ) -> *mut VSNode,
    >,
    pub mapSetNode: ::std::option::Option<
        unsafe extern "C" fn(
            map: *mut VSMap,
            key: *const ::std::os::raw::c_char,
            node: *mut VSNode,
            append: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub mapConsumeNode: ::std::option::Option<
        unsafe extern "C" fn(
            map: *mut VSMap,
            key: *const ::std::os::raw::c_char,
            node: *mut VSNode,
            append: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub mapGetFrame: ::std::option::Option<
        unsafe extern "C" fn(
            map: *const VSMap,
            key: *const ::std::os::raw::c_char,
            index: ::std::os::raw::c_int,
            error: *mut ::std::os::raw::c_int,
        ) -> *const VSFrame,
    >,
    pub mapSetFrame: ::std::option::Option<
        unsafe extern "C" fn(
            map: *mut VSMap,
            key: *const ::std::os::raw::c_char,
            f: *const VSFrame,
            append: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub mapConsumeFrame: ::std::option::Option<
        unsafe extern "C" fn(
            map: *mut VSMap,
            key: *const ::std::os::raw::c_char,
            f: *const VSFrame,
            append: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub mapGetFunction: ::std::option::Option<
        unsafe extern "C" fn(
            map: *const VSMap,
            key: *const ::std::os::raw::c_char,
            index: ::std::os::raw::c_int,
            error: *mut ::std::os::raw::c_int,
        ) -> *mut VSFunction,
    >,
    pub mapSetFunction: ::std::option::Option<
        unsafe extern "C" fn(
            map: *mut VSMap,
            key: *const ::std::os::raw::c_char,
            func: *mut VSFunction,
            append: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub mapConsumeFunction: ::std::option::Option<
        unsafe extern "C" fn(
            map: *mut VSMap,
            key: *const ::std::os::raw::c_char,
            func: *mut VSFunction,
            append: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub registerFunction: ::std::option::Option<
        unsafe extern "C" fn(
            name: *const ::std::os::raw::c_char,
            args: *const ::std::os::raw::c_char,
            returnType: *const ::std::os::raw::c_char,
            argsFunc: VSPublicFunction,
            functionData: *mut ::std::os::raw::c_void,
            plugin: *mut VSPlugin,
        ) -> ::std::os::raw::c_int,
    >,
    pub getPluginByID: ::std::option::Option<
        unsafe extern "C" fn(
            identifier: *const ::std::os::raw::c_char,
            core: *mut VSCore,
        ) -> *mut VSPlugin,
    >,
    pub getPluginByNamespace: ::std::option::Option<
        unsafe extern "C" fn(ns: *const ::std::os::raw::c_char, core: *mut VSCore) -> *mut VSPlugin,
    >,
    pub getNextPlugin: ::std::option::Option<
        unsafe extern "C" fn(plugin: *mut VSPlugin, core: *mut VSCore) -> *mut VSPlugin,
    >,
    pub getPluginName: ::std::option::Option<
        unsafe extern "C" fn(plugin: *mut VSPlugin) -> *const ::std::os::raw::c_char,
    >,
    pub getPluginID: ::std::option::Option<
        unsafe extern "C" fn(plugin: *mut VSPlugin) -> *const ::std::os::raw::c_char,
    >,
    pub getPluginNamespace: ::std::option::Option<
        unsafe extern "C" fn(plugin: *mut VSPlugin) -> *const ::std::os::raw::c_char,
    >,
    pub getNextPluginFunction: ::std::option::Option<
        unsafe extern "C" fn(
            func: *mut VSPluginFunction,
            plugin: *mut VSPlugin,
        ) -> *mut VSPluginFunction,
    >,
    pub getPluginFunctionByName: ::std::option::Option<
        unsafe extern "C" fn(
            name: *const ::std::os::raw::c_char,
            plugin: *mut VSPlugin,
        ) -> *mut VSPluginFunction,
    >,
    pub getPluginFunctionName: ::std::option::Option<
        unsafe extern "C" fn(func: *mut VSPluginFunction) -> *const ::std::os::raw::c_char,
    >,
    pub getPluginFunctionArguments: ::std::option::Option<
        unsafe extern "C" fn(func: *mut VSPluginFunction) -> *const ::std::os::raw::c_char,
    >,
    pub getPluginFunctionReturnType: ::std::option::Option<
        unsafe extern "C" fn(func: *mut VSPluginFunction) -> *const ::std::os::raw::c_char,
    >,
    pub getPluginPath: ::std::option::Option<
        unsafe extern "C" fn(plugin: *const VSPlugin) -> *const ::std::os::raw::c_char,
    >,
    pub getPluginVersion: ::std::option::Option<
        unsafe extern "C" fn(plugin: *const VSPlugin) -> ::std::os::raw::c_int,
    >,
    pub invoke: ::std::option::Option<
        unsafe extern "C" fn(
            plugin: *mut VSPlugin,
            name: *const ::std::os::raw::c_char,
            args: *const VSMap,
        ) -> *mut VSMap,
    >,
    pub createCore:
        ::std::option::Option<unsafe extern "C" fn(flags: ::std::os::raw::c_int) -> *mut VSCore>,
    pub freeCore: ::std::option::Option<unsafe extern "C" fn(core: *mut VSCore)>,
    pub setMaxCacheSize:
        ::std::option::Option<unsafe extern "C" fn(bytes: i64, core: *mut VSCore) -> i64>,
    pub setThreadCount: ::std::option::Option<
        unsafe extern "C" fn(
            threads: ::std::os::raw::c_int,
            core: *mut VSCore,
        ) -> ::std::os::raw::c_int,
    >,
    pub getCoreInfo:
        ::std::option::Option<unsafe extern "C" fn(core: *mut VSCore, info: *mut VSCoreInfo)>,
    pub getAPIVersion: ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>,
    pub logMessage: ::std::option::Option<
        unsafe extern "C" fn(
            msgType: ::std::os::raw::c_int,
            msg: *const ::std::os::raw::c_char,
            core: *mut VSCore,
        ),
    >,
    pub addLogHandler: ::std::option::Option<
        unsafe extern "C" fn(
            handler: VSLogHandler,
            free: VSLogHandlerFree,
            userData: *mut ::std::os::raw::c_void,
            core: *mut VSCore,
        ) -> *mut VSLogHandle,
    >,
    pub removeLogHandler: ::std::option::Option<
        unsafe extern "C" fn(handle: *mut VSLogHandle, core: *mut VSCore) -> ::std::os::raw::c_int,
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VSAPI"][::std::mem::size_of::<VSAPI>() - 848usize];
    ["Alignment of VSAPI"][::std::mem::align_of::<VSAPI>() - 8usize];
    ["Offset of field: VSAPI::createVideoFilter"]
        [::std::mem::offset_of!(VSAPI, createVideoFilter) - 0usize];
    ["Offset of field: VSAPI::createVideoFilter2"]
        [::std::mem::offset_of!(VSAPI, createVideoFilter2) - 8usize];
    ["Offset of field: VSAPI::createAudioFilter"]
        [::std::mem::offset_of!(VSAPI, createAudioFilter) - 16usize];
    ["Offset of field: VSAPI::createAudioFilter2"]
        [::std::mem::offset_of!(VSAPI, createAudioFilter2) - 24usize];
    ["Offset of field: VSAPI::setLinearFilter"]
        [::std::mem::offset_of!(VSAPI, setLinearFilter) - 32usize];
    ["Offset of field: VSAPI::setCacheMode"][::std::mem::offset_of!(VSAPI, setCacheMode) - 40usize];
    ["Offset of field: VSAPI::setCacheOptions"]
        [::std::mem::offset_of!(VSAPI, setCacheOptions) - 48usize];
    ["Offset of field: VSAPI::freeNode"][::std::mem::offset_of!(VSAPI, freeNode) - 56usize];
    ["Offset of field: VSAPI::addNodeRef"][::std::mem::offset_of!(VSAPI, addNodeRef) - 64usize];
    ["Offset of field: VSAPI::getNodeType"][::std::mem::offset_of!(VSAPI, getNodeType) - 72usize];
    ["Offset of field: VSAPI::getVideoInfo"][::std::mem::offset_of!(VSAPI, getVideoInfo) - 80usize];
    ["Offset of field: VSAPI::getAudioInfo"][::std::mem::offset_of!(VSAPI, getAudioInfo) - 88usize];
    ["Offset of field: VSAPI::newVideoFrame"]
        [::std::mem::offset_of!(VSAPI, newVideoFrame) - 96usize];
    ["Offset of field: VSAPI::newVideoFrame2"]
        [::std::mem::offset_of!(VSAPI, newVideoFrame2) - 104usize];
    ["Offset of field: VSAPI::newAudioFrame"]
        [::std::mem::offset_of!(VSAPI, newAudioFrame) - 112usize];
    ["Offset of field: VSAPI::newAudioFrame2"]
        [::std::mem::offset_of!(VSAPI, newAudioFrame2) - 120usize];
    ["Offset of field: VSAPI::freeFrame"][::std::mem::offset_of!(VSAPI, freeFrame) - 128usize];
    ["Offset of field: VSAPI::addFrameRef"][::std::mem::offset_of!(VSAPI, addFrameRef) - 136usize];
    ["Offset of field: VSAPI::copyFrame"][::std::mem::offset_of!(VSAPI, copyFrame) - 144usize];
    ["Offset of field: VSAPI::getFramePropertiesRO"]
        [::std::mem::offset_of!(VSAPI, getFramePropertiesRO) - 152usize];
    ["Offset of field: VSAPI::getFramePropertiesRW"]
        [::std::mem::offset_of!(VSAPI, getFramePropertiesRW) - 160usize];
    ["Offset of field: VSAPI::getStride"][::std::mem::offset_of!(VSAPI, getStride) - 168usize];
    ["Offset of field: VSAPI::getReadPtr"][::std::mem::offset_of!(VSAPI, getReadPtr) - 176usize];
    ["Offset of field: VSAPI::getWritePtr"][::std::mem::offset_of!(VSAPI, getWritePtr) - 184usize];
    ["Offset of field: VSAPI::getVideoFrameFormat"]
        [::std::mem::offset_of!(VSAPI, getVideoFrameFormat) - 192usize];
    ["Offset of field: VSAPI::getAudioFrameFormat"]
        [::std::mem::offset_of!(VSAPI, getAudioFrameFormat) - 200usize];
    ["Offset of field: VSAPI::getFrameType"]
        [::std::mem::offset_of!(VSAPI, getFrameType) - 208usize];
    ["Offset of field: VSAPI::getFrameWidth"]
        [::std::mem::offset_of!(VSAPI, getFrameWidth) - 216usize];
    ["Offset of field: VSAPI::getFrameHeight"]
        [::std::mem::offset_of!(VSAPI, getFrameHeight) - 224usize];
    ["Offset of field: VSAPI::getFrameLength"]
        [::std::mem::offset_of!(VSAPI, getFrameLength) - 232usize];
    ["Offset of field: VSAPI::getVideoFormatName"]
        [::std::mem::offset_of!(VSAPI, getVideoFormatName) - 240usize];
    ["Offset of field: VSAPI::getAudioFormatName"]
        [::std::mem::offset_of!(VSAPI, getAudioFormatName) - 248usize];
    ["Offset of field: VSAPI::queryVideoFormat"]
        [::std::mem::offset_of!(VSAPI, queryVideoFormat) - 256usize];
    ["Offset of field: VSAPI::queryAudioFormat"]
        [::std::mem::offset_of!(VSAPI, queryAudioFormat) - 264usize];
    ["Offset of field: VSAPI::queryVideoFormatID"]
        [::std::mem::offset_of!(VSAPI, queryVideoFormatID) - 272usize];
    ["Offset of field: VSAPI::getVideoFormatByID"]
        [::std::mem::offset_of!(VSAPI, getVideoFormatByID) - 280usize];
    ["Offset of field: VSAPI::getFrame"][::std::mem::offset_of!(VSAPI, getFrame) - 288usize];
    ["Offset of field: VSAPI::getFrameAsync"]
        [::std::mem::offset_of!(VSAPI, getFrameAsync) - 296usize];
    ["Offset of field: VSAPI::getFrameFilter"]
        [::std::mem::offset_of!(VSAPI, getFrameFilter) - 304usize];
    ["Offset of field: VSAPI::requestFrameFilter"]
        [::std::mem::offset_of!(VSAPI, requestFrameFilter) - 312usize];
    ["Offset of field: VSAPI::releaseFrameEarly"]
        [::std::mem::offset_of!(VSAPI, releaseFrameEarly) - 320usize];
    ["Offset of field: VSAPI::cacheFrame"][::std::mem::offset_of!(VSAPI, cacheFrame) - 328usize];
    ["Offset of field: VSAPI::setFilterError"]
        [::std::mem::offset_of!(VSAPI, setFilterError) - 336usize];
    ["Offset of field: VSAPI::createFunction"]
        [::std::mem::offset_of!(VSAPI, createFunction) - 344usize];
    ["Offset of field: VSAPI::freeFunction"]
        [::std::mem::offset_of!(VSAPI, freeFunction) - 352usize];
    ["Offset of field: VSAPI::addFunctionRef"]
        [::std::mem::offset_of!(VSAPI, addFunctionRef) - 360usize];
    ["Offset of field: VSAPI::callFunction"]
        [::std::mem::offset_of!(VSAPI, callFunction) - 368usize];
    ["Offset of field: VSAPI::createMap"][::std::mem::offset_of!(VSAPI, createMap) - 376usize];
    ["Offset of field: VSAPI::freeMap"][::std::mem::offset_of!(VSAPI, freeMap) - 384usize];
    ["Offset of field: VSAPI::clearMap"][::std::mem::offset_of!(VSAPI, clearMap) - 392usize];
    ["Offset of field: VSAPI::copyMap"][::std::mem::offset_of!(VSAPI, copyMap) - 400usize];
    ["Offset of field: VSAPI::mapSetError"][::std::mem::offset_of!(VSAPI, mapSetError) - 408usize];
    ["Offset of field: VSAPI::mapGetError"][::std::mem::offset_of!(VSAPI, mapGetError) - 416usize];
    ["Offset of field: VSAPI::mapNumKeys"][::std::mem::offset_of!(VSAPI, mapNumKeys) - 424usize];
    ["Offset of field: VSAPI::mapGetKey"][::std::mem::offset_of!(VSAPI, mapGetKey) - 432usize];
    ["Offset of field: VSAPI::mapDeleteKey"]
        [::std::mem::offset_of!(VSAPI, mapDeleteKey) - 440usize];
    ["Offset of field: VSAPI::mapNumElements"]
        [::std::mem::offset_of!(VSAPI, mapNumElements) - 448usize];
    ["Offset of field: VSAPI::mapGetType"][::std::mem::offset_of!(VSAPI, mapGetType) - 456usize];
    ["Offset of field: VSAPI::mapSetEmpty"][::std::mem::offset_of!(VSAPI, mapSetEmpty) - 464usize];
    ["Offset of field: VSAPI::mapGetInt"][::std::mem::offset_of!(VSAPI, mapGetInt) - 472usize];
    ["Offset of field: VSAPI::mapGetIntSaturated"]
        [::std::mem::offset_of!(VSAPI, mapGetIntSaturated) - 480usize];
    ["Offset of field: VSAPI::mapGetIntArray"]
        [::std::mem::offset_of!(VSAPI, mapGetIntArray) - 488usize];
    ["Offset of field: VSAPI::mapSetInt"][::std::mem::offset_of!(VSAPI, mapSetInt) - 496usize];
    ["Offset of field: VSAPI::mapSetIntArray"]
        [::std::mem::offset_of!(VSAPI, mapSetIntArray) - 504usize];
    ["Offset of field: VSAPI::mapGetFloat"][::std::mem::offset_of!(VSAPI, mapGetFloat) - 512usize];
    ["Offset of field: VSAPI::mapGetFloatSaturated"]
        [::std::mem::offset_of!(VSAPI, mapGetFloatSaturated) - 520usize];
    ["Offset of field: VSAPI::mapGetFloatArray"]
        [::std::mem::offset_of!(VSAPI, mapGetFloatArray) - 528usize];
    ["Offset of field: VSAPI::mapSetFloat"][::std::mem::offset_of!(VSAPI, mapSetFloat) - 536usize];
    ["Offset of field: VSAPI::mapSetFloatArray"]
        [::std::mem::offset_of!(VSAPI, mapSetFloatArray) - 544usize];
    ["Offset of field: VSAPI::mapGetData"][::std::mem::offset_of!(VSAPI, mapGetData) - 552usize];
    ["Offset of field: VSAPI::mapGetDataSize"]
        [::std::mem::offset_of!(VSAPI, mapGetDataSize) - 560usize];
    ["Offset of field: VSAPI::mapGetDataTypeHint"]
        [::std::mem::offset_of!(VSAPI, mapGetDataTypeHint) - 568usize];
    ["Offset of field: VSAPI::mapSetData"][::std::mem::offset_of!(VSAPI, mapSetData) - 576usize];
    ["Offset of field: VSAPI::mapGetNode"][::std::mem::offset_of!(VSAPI, mapGetNode) - 584usize];
    ["Offset of field: VSAPI::mapSetNode"][::std::mem::offset_of!(VSAPI, mapSetNode) - 592usize];
    ["Offset of field: VSAPI::mapConsumeNode"]
        [::std::mem::offset_of!(VSAPI, mapConsumeNode) - 600usize];
    ["Offset of field: VSAPI::mapGetFrame"][::std::mem::offset_of!(VSAPI, mapGetFrame) - 608usize];
    ["Offset of field: VSAPI::mapSetFrame"][::std::mem::offset_of!(VSAPI, mapSetFrame) - 616usize];
    ["Offset of field: VSAPI::mapConsumeFrame"]
        [::std::mem::offset_of!(VSAPI, mapConsumeFrame) - 624usize];
    ["Offset of field: VSAPI::mapGetFunction"]
        [::std::mem::offset_of!(VSAPI, mapGetFunction) - 632usize];
    ["Offset of field: VSAPI::mapSetFunction"]
        [::std::mem::offset_of!(VSAPI, mapSetFunction) - 640usize];
    ["Offset of field: VSAPI::mapConsumeFunction"]
        [::std::mem::offset_of!(VSAPI, mapConsumeFunction) - 648usize];
    ["Offset of field: VSAPI::registerFunction"]
        [::std::mem::offset_of!(VSAPI, registerFunction) - 656usize];
    ["Offset of field: VSAPI::getPluginByID"]
        [::std::mem::offset_of!(VSAPI, getPluginByID) - 664usize];
    ["Offset of field: VSAPI::getPluginByNamespace"]
        [::std::mem::offset_of!(VSAPI, getPluginByNamespace) - 672usize];
    ["Offset of field: VSAPI::getNextPlugin"]
        [::std::mem::offset_of!(VSAPI, getNextPlugin) - 680usize];
    ["Offset of field: VSAPI::getPluginName"]
        [::std::mem::offset_of!(VSAPI, getPluginName) - 688usize];
    ["Offset of field: VSAPI::getPluginID"][::std::mem::offset_of!(VSAPI, getPluginID) - 696usize];
    ["Offset of field: VSAPI::getPluginNamespace"]
        [::std::mem::offset_of!(VSAPI, getPluginNamespace) - 704usize];
    ["Offset of field: VSAPI::getNextPluginFunction"]
        [::std::mem::offset_of!(VSAPI, getNextPluginFunction) - 712usize];
    ["Offset of field: VSAPI::getPluginFunctionByName"]
        [::std::mem::offset_of!(VSAPI, getPluginFunctionByName) - 720usize];
    ["Offset of field: VSAPI::getPluginFunctionName"]
        [::std::mem::offset_of!(VSAPI, getPluginFunctionName) - 728usize];
    ["Offset of field: VSAPI::getPluginFunctionArguments"]
        [::std::mem::offset_of!(VSAPI, getPluginFunctionArguments) - 736usize];
    ["Offset of field: VSAPI::getPluginFunctionReturnType"]
        [::std::mem::offset_of!(VSAPI, getPluginFunctionReturnType) - 744usize];
    ["Offset of field: VSAPI::getPluginPath"]
        [::std::mem::offset_of!(VSAPI, getPluginPath) - 752usize];
    ["Offset of field: VSAPI::getPluginVersion"]
        [::std::mem::offset_of!(VSAPI, getPluginVersion) - 760usize];
    ["Offset of field: VSAPI::invoke"][::std::mem::offset_of!(VSAPI, invoke) - 768usize];
    ["Offset of field: VSAPI::createCore"][::std::mem::offset_of!(VSAPI, createCore) - 776usize];
    ["Offset of field: VSAPI::freeCore"][::std::mem::offset_of!(VSAPI, freeCore) - 784usize];
    ["Offset of field: VSAPI::setMaxCacheSize"]
        [::std::mem::offset_of!(VSAPI, setMaxCacheSize) - 792usize];
    ["Offset of field: VSAPI::setThreadCount"]
        [::std::mem::offset_of!(VSAPI, setThreadCount) - 800usize];
    ["Offset of field: VSAPI::getCoreInfo"][::std::mem::offset_of!(VSAPI, getCoreInfo) - 808usize];
    ["Offset of field: VSAPI::getAPIVersion"]
        [::std::mem::offset_of!(VSAPI, getAPIVersion) - 816usize];
    ["Offset of field: VSAPI::logMessage"][::std::mem::offset_of!(VSAPI, logMessage) - 824usize];
    ["Offset of field: VSAPI::addLogHandler"]
        [::std::mem::offset_of!(VSAPI, addLogHandler) - 832usize];
    ["Offset of field: VSAPI::removeLogHandler"]
        [::std::mem::offset_of!(VSAPI, removeLogHandler) - 840usize];
};
unsafe extern "C" {
    pub fn getVapourSynthAPI(version: ::std::os::raw::c_int) -> *const VSAPI;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VSScript {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VSSCRIPTAPI {
    pub getAPIVersion: ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>,
    pub getVSAPI:
        ::std::option::Option<unsafe extern "C" fn(version: ::std::os::raw::c_int) -> *const VSAPI>,
    pub createScript:
        ::std::option::Option<unsafe extern "C" fn(core: *mut VSCore) -> *mut VSScript>,
    pub getCore: ::std::option::Option<unsafe extern "C" fn(handle: *mut VSScript) -> *mut VSCore>,
    pub evaluateBuffer: ::std::option::Option<
        unsafe extern "C" fn(
            handle: *mut VSScript,
            buffer: *const ::std::os::raw::c_char,
            scriptFilename: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub evaluateFile: ::std::option::Option<
        unsafe extern "C" fn(
            handle: *mut VSScript,
            scriptFilename: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub getError: ::std::option::Option<
        unsafe extern "C" fn(handle: *mut VSScript) -> *const ::std::os::raw::c_char,
    >,
    pub getExitCode:
        ::std::option::Option<unsafe extern "C" fn(handle: *mut VSScript) -> ::std::os::raw::c_int>,
    pub getVariable: ::std::option::Option<
        unsafe extern "C" fn(
            handle: *mut VSScript,
            name: *const ::std::os::raw::c_char,
            dst: *mut VSMap,
        ) -> ::std::os::raw::c_int,
    >,
    pub setVariables: ::std::option::Option<
        unsafe extern "C" fn(handle: *mut VSScript, vars: *const VSMap) -> ::std::os::raw::c_int,
    >,
    pub getOutputNode: ::std::option::Option<
        unsafe extern "C" fn(handle: *mut VSScript, index: ::std::os::raw::c_int) -> *mut VSNode,
    >,
    pub getOutputAlphaNode: ::std::option::Option<
        unsafe extern "C" fn(handle: *mut VSScript, index: ::std::os::raw::c_int) -> *mut VSNode,
    >,
    pub getAltOutputMode: ::std::option::Option<
        unsafe extern "C" fn(
            handle: *mut VSScript,
            index: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub freeScript: ::std::option::Option<unsafe extern "C" fn(handle: *mut VSScript)>,
    pub evalSetWorkingDir: ::std::option::Option<
        unsafe extern "C" fn(handle: *mut VSScript, setCWD: ::std::os::raw::c_int),
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VSSCRIPTAPI"][::std::mem::size_of::<VSSCRIPTAPI>() - 120usize];
    ["Alignment of VSSCRIPTAPI"][::std::mem::align_of::<VSSCRIPTAPI>() - 8usize];
    ["Offset of field: VSSCRIPTAPI::getAPIVersion"]
        [::std::mem::offset_of!(VSSCRIPTAPI, getAPIVersion) - 0usize];
    ["Offset of field: VSSCRIPTAPI::getVSAPI"]
        [::std::mem::offset_of!(VSSCRIPTAPI, getVSAPI) - 8usize];
    ["Offset of field: VSSCRIPTAPI::createScript"]
        [::std::mem::offset_of!(VSSCRIPTAPI, createScript) - 16usize];
    ["Offset of field: VSSCRIPTAPI::getCore"]
        [::std::mem::offset_of!(VSSCRIPTAPI, getCore) - 24usize];
    ["Offset of field: VSSCRIPTAPI::evaluateBuffer"]
        [::std::mem::offset_of!(VSSCRIPTAPI, evaluateBuffer) - 32usize];
    ["Offset of field: VSSCRIPTAPI::evaluateFile"]
        [::std::mem::offset_of!(VSSCRIPTAPI, evaluateFile) - 40usize];
    ["Offset of field: VSSCRIPTAPI::getError"]
        [::std::mem::offset_of!(VSSCRIPTAPI, getError) - 48usize];
    ["Offset of field: VSSCRIPTAPI::getExitCode"]
        [::std::mem::offset_of!(VSSCRIPTAPI, getExitCode) - 56usize];
    ["Offset of field: VSSCRIPTAPI::getVariable"]
        [::std::mem::offset_of!(VSSCRIPTAPI, getVariable) - 64usize];
    ["Offset of field: VSSCRIPTAPI::setVariables"]
        [::std::mem::offset_of!(VSSCRIPTAPI, setVariables) - 72usize];
    ["Offset of field: VSSCRIPTAPI::getOutputNode"]
        [::std::mem::offset_of!(VSSCRIPTAPI, getOutputNode) - 80usize];
    ["Offset of field: VSSCRIPTAPI::getOutputAlphaNode"]
        [::std::mem::offset_of!(VSSCRIPTAPI, getOutputAlphaNode) - 88usize];
    ["Offset of field: VSSCRIPTAPI::getAltOutputMode"]
        [::std::mem::offset_of!(VSSCRIPTAPI, getAltOutputMode) - 96usize];
    ["Offset of field: VSSCRIPTAPI::freeScript"]
        [::std::mem::offset_of!(VSSCRIPTAPI, freeScript) - 104usize];
    ["Offset of field: VSSCRIPTAPI::evalSetWorkingDir"]
        [::std::mem::offset_of!(VSSCRIPTAPI, evalSetWorkingDir) - 112usize];
};
unsafe extern "C" {
    pub fn getVSScriptAPI(version: ::std::os::raw::c_int) -> *const VSSCRIPTAPI;
}
