//! Raw bindings to [VapourSynth](https://github.com/vapoursynth/vapoursynth).

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]

// The bindings can be regenerated by using the `generate-bindings.sh` script,
// or manually by copying the file generated by the `bindgen` feature.
include!("bindings.rs");
