name: vapoursynth

on: [push, pull_request]

jobs:
  clippy-rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Run rustfmt
        run: cargo fmt --all -- --check
      - name: Run clippy on all tests
        run: cargo clippy --all --all-targets --all-features --exclude sample-plugin -- -D warnings
      - name: Run clippy on the sample-plugin
        run: cargo clippy --all-targets --package sample-plugin -- -D warnings

  unix-tests:
    strategy:
      fail-fast: false

      matrix:
        version: ['73', '74']
        toolchain:
          - stable-aarch64-apple-darwin
          - stable-x86_64-unknown-linux-gnu
          - stable-aarch64-unknown-linux-gnu
        include:
          - toolchain: stable-aarch64-apple-darwin
            os: macOS-latest
          - toolchain: stable-x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - toolchain: stable-aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
        exclude:
          # FIXME: Look into macOS library paths for R73
          - toolchain: stable-aarch64-apple-darwin
            version: '73'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.14
          activate-environment: ${{ matrix.version != '73' }}

      - name: Install VapourSynth Python Package
        if: matrix.version != '73'
        run: |
          uv pip install vapoursynth==${{ matrix.version }}
          vapoursynth config
          echo "VSSCRIPT_PATH=$(vapoursynth get-vsscript)" >> $GITHUB_ENV

      - name: Build and install VapourSynth R73
        if: >
          matrix.version == '73' &&
          (matrix.toolchain == 'stable-x86_64-unknown-linux-gnu' || matrix.toolchain == 'stable-aarch64-unknown-linux-gnu')
        run: |
          build/script.sh ${{ matrix.version }}
          echo "LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "VAPOURSYNTH_LIB_DIR=/usr/local/lib" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Run tests
        run: |
          cd vapoursynth
          uv run ../build/run-tests.py --requires-compat=${{ matrix.version == '73' }}
      - name: Run sample-plugin tests
        run: |
          cd sample-plugin
          cargo build --verbose
          cargo run ${{ matrix.version == '73' && '--features vsscript-r73-compat' }} --verbose --bin test
      - name: Run doc
        run: |
          cargo doc --all-features --verbose
      - name: Copy index into the target directory
        if: matrix.toolchain == 'stable-x86_64-unknown-linux-gnu'
        run: |
          cp build/index.html target/doc
      - name: Deploy documentation
        if: >
          matrix.toolchain == 'stable-x86_64-unknown-linux-gnu' &&
          github.event_name == 'push' &&
          github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc

  windows-tests:
    strategy:
      fail-fast: false

      matrix:
        version: ['73', '74']
        toolchain:
          - stable-x86_64-pc-windows-msvc
          - stable-x86_64-pc-windows-gnu
        include:
          - toolchain: stable-x86_64-pc-windows-msvc
            arch: x86_64
          - toolchain: stable-x86_64-pc-windows-gnu
            arch: x86_64

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.14
          activate-environment: ${{ matrix.version != '73' }}

      - name: Install VapourSynth Portable
        if: matrix.arch == 'x86_64' && matrix.version == '73'
        run: |
          build/windows-script.ps1
      - name: Add VS to PATH
        if: matrix.version == '73'
        shell: bash
        run: |
          echo "C:\Program Files\VapourSynth" >> $GITHUB_PATH
      - name: Install VapourSynth Python Package
        if: matrix.version != '73'
        run: |
          uv pip install vapoursynth==${{ matrix.version }}
          vapoursynth config
          "VSSCRIPT_PATH=$(vapoursynth get-vsscript)" >> "$env:GITHUB_ENV"

      - run: rustup set auto-self-update disable
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Run tests
        run: |
          cd vapoursynth
          uv run ../build/run-tests.py
      - name: Build sample-plugin
        run: |
          cd sample-plugin
          cargo build --verbose
      - name: Run sample-plugin tests
        # https://github.com/rust-lang/rust/issues/50176
        run: |
          $Env:Path += ";C:\Program Files\VapourSynth;"
          cd sample-plugin
          cargo run --verbose --bin test
      - name: Run doc
        run: cargo doc --all-features --verbose
